### ISSUE TITLE
Release 0.4.28 for Fix with Recent Gradle Versions

### ISSUE THREAD

**Issue by Parthib** [khjde1207/tesseract_ocr#50]
Hello,

The current latest (0.4.27) does not include the latest commit involving the fix for gradle 8+, which is causing my Android builds to fail. My current workaround is to do this for my dependency:

```
  flutter_tesseract_ocr:
    git:
      url: https://github.com/khjde1207/tesseract_ocr
      ref: bcce52ca8d2d01834af83df4bfa42561eecb7662
```

Could you release a v0.4.28 that includes the latest commit in the release? Thanks!
